server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: pfgateway
  cloud:
    gateway:
      routes:
        - id: customerservice
          uri: http://localhost:8082
          predicates:
            - Path=/customerservice
        - id: orderservice
          uri: http://localhost:8083
          predicates:
            - Path=/orderservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
