server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: pfgateway
  cloud:
    gateway:
      routes:
        - id: customerservice
          uri: http://localhost:8082
          predicates:
            - Path=/customerservice
        - id: orderservice
          uri: http://localhost:8083
          predicates:
            - Path=/orderservice
      # Aggregation configuration
      filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
